services:
  postgres:
    image: postgres:16-alpine
    container_name: ventalocal-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ventalocal-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: ventalocal-search
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: ventalocal-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data

  api:
    image: ghcr.io/ventalocal/api:latest
    container_name: ventalocal-api
    env_file: .env.production
    depends_on:
      - postgres
      - redis
      - meilisearch
      - minio
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 6

  gateway:
    image: nginx:1.27-alpine
    container_name: ventalocal-gateway
    depends_on:
      - api
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  pg_data:
  redis_data:
  meili_data:
  minio_data:
